"""Packaged entry point for PyInstaller-based standalone executable.

When run as a .exe (via PyInstaller --onefile), this handles:
  - Changing CWD to the exe directory BEFORE any project imports
  - Auto-creating .env from an embedded template if missing
  - Setting TIKTOKEN_CACHE_DIR for the bundled encoding cache (via sys._MEIPASS)
  - Printing a startup banner with Claude Code connection instructions
  - Starting uvicorn with clean subprocess shutdown via kill_all_best_effort()
"""

import os
import sys
from pathlib import Path


# Embedded .env template - created fresh when .env is missing.
# This way the exe works standalone with no extra files needed.
_ENV_TEMPLATE = """# NVIDIA NIM API Key (REQUIRED)
# Get one at https://build.nvidia.com/settings/api-keys
NVIDIA_NIM_API_KEY="<replaceme>"

# Port for the proxy server (default: 8082)
PORT=8082

# NIM model - single, or comma-separated for multi-tier:
#   Single: MODEL="deepseek-ai/deepseek-v4-flash"
#   Two:    MODEL="qwen/qwen3-coder-480b-a35b-instruct,deepseek-ai/deepseek-v4-flash"
#   Three:  MODEL="qwen/qwen3-coder-480b-a35b-instruct,minimaxai/minimax-m2.7,deepseek-ai/deepseek-v4-flash"
MODEL="deepseek-ai/deepseek-v4-flash"

# Proxy API key - optional, auto-generated if blank or "<replaceme>"
PROXY_API_KEY="<replaceme>"

# NIM thinking mode - "true" for DeepSeek V4 Flash, "false" for Pro/models without reasoning
NIM_THINKING=true
"""


def _exe_dir() -> Path:
    """Return the directory containing the executable (or this script in dev)."""
    if getattr(sys, "frozen", False):
        return Path(sys.executable).parent.resolve()
    return Path(__file__).parent.resolve()


def _ensure_env_file(exe_dir: Path) -> None:
    """Auto-create .env from embedded template if it doesn't exist."""
    env_path = exe_dir / ".env"
    if env_path.exists():
        return

    print("=" * 60)
    print("  NIMbus - First Run Setup")
    print("=" * 60)
    print()
    print(f"  Created: {env_path}")
    print()
    print("  Open this file in a text editor and set your")
    print("  NVIDIA_NIM_API_KEY (get one at the URL below),")
    print("  then save the file and press Enter.")
    print()
    print("  Required: NVIDIA_NIM_API_KEY")
    print("  Optional: PORT, MODEL, PROXY_API_KEY, etc.")
    print()
    print("  Get your key: https://build.nvidia.com/settings/api-keys")
    print()

    env_path.write_text(_ENV_TEMPLATE, encoding="utf-8")

    input("  Press Enter after editing .env to continue, or Ctrl+C to exit...")
    if not env_path.exists():
        print("  .env was deleted. Exiting.")
        sys.exit(1)


def _print_banner(settings) -> None:
    """Print startup banner with connection instructions."""
    host = settings.host
    port = settings.port
    api_key = settings.proxy_api_key or "<auto-generated>"
    base_url = f"http://{host}:{port}"

    print()
    print("=" * 60)
    print("  NIMbus Proxy Server v2.0.4  (Standalone)")
    print("=" * 60)
    print(f"  Host: {host}")
    print(f"  Port: {port}")

    model_list = settings.model_list
    tiers = ["Default/Sonnet", "Opus", "Haiku"]
    if len(model_list) == 1:
        print(f"  Model: {model_list[0]} (all tiers)")
    else:
        for i, tier in enumerate(tiers):
            if i < len(model_list):
                print(f"  {tier}: {model_list[i]}")

    print(f"  Discord Bot: {'Enabled' if settings.discord_enabled else 'Disabled'}")
    print()
    print("  TO CONNECT CLAUDE CODE:")
    print("-" * 40)
    print(f'  set ANTHROPIC_AUTH_TOKEN={api_key}')
    print(f'  set ANTHROPIC_BASE_URL={base_url}')
    print(f'  claude')
    print()
    print("  Press Ctrl+C to stop the server.")
    print("=" * 60)
    print()


def _run_mcp_server() -> None:
    """Run the MCP server with stdio transport."""
    from mcp_server import mcp
    print("Starting NIMbus MCP Server (stdio transport)...", file=sys.stderr)
    mcp.run(transport="stdio")


def main() -> None:
    """Entry point for the packaged executable."""
    # --- Step 1: Change CWD to exe directory BEFORE any project imports ---
    exe_dir = _exe_dir()
    os.chdir(str(exe_dir))

    # --- Step 2: Check for --swapper flag ---
    if "--swapper" in sys.argv:
        os.environ["SWAPPER_ENABLED"] = "true"

    # --- Step 3: Check for --mcp flag ---
    if "--mcp" in sys.argv:
        _run_mcp_server()
        sys.exit(0)

    # --- Step 4: Check for --init interactive setup wizard ---
    if "--init" in sys.argv:
        from setup_wizard import run_wizard
        run_wizard(exe_dir, sys.argv)
        sys.exit(0)

    # --- Step 5: Auto-create .env if missing ---
    _ensure_env_file(exe_dir)

    # --- Step 6: Point tiktoken at bundled cache ---
    # In --onefile mode, data files are extracted to sys._MEIPASS
    if getattr(sys, "frozen", False):
        meipass = Path(sys._MEIPASS)  # type: ignore[attr-defined]
        tiktoken_cache = meipass / "tiktoken_cache"
        if tiktoken_cache.exists():
            os.environ["TIKTOKEN_CACHE_DIR"] = str(tiktoken_cache)

    # --- Step 7: Import project code (now CWD and env vars are correct) ---
    from config.settings import get_settings
    from config.logging_config import configure_logging

    settings = get_settings()
    configure_logging(settings.log_file)

    # --- Step 8: Print startup banner ---
    _print_banner(settings)

    # --- Step 9: Start uvicorn ---
    import uvicorn

    from api.app import app
    from cli.process_registry import kill_all_best_effort

    try:
        uvicorn.run(
            app,
            host=settings.host,
            port=settings.port,
            log_level="info",
            timeout_graceful_shutdown=5,
        )
    finally:
        kill_all_best_effort()


if __name__ == "__main__":
    main()
